// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get a summary of Marwin Emia \u2014 AI Automation & Workflow Specialist. Returns headline, bio, years of experience, and key stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "Marwin G. Emia",
          title: "AI Automation & Workflow Specialist",
          headline: "I automate businesses with AI & smart workflows.",
          bio: "AI & Workflow Automation Specialist who designs GoHighLevel, n8n, Make.com, and Zapier systems with AI integrations (ChatGPT, Claude, Gemini, Grok) that save time, streamline operations, and drive real business growth.",
          stats: {
            years_experience: "7+",
            workflows_built: "50+",
            tools_mastered: "35+",
            automation_executions: "2,000+",
            failure_rate: "1.3% across 2,000+ production executions"
          },
          website: "https://marwinai.com"
        }, null, 2)
      }
    ]
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
var services = [
  { name: "AI Automation Systems", description: "Custom AI-powered workflows using ChatGPT, Claude, Gemini, and Grok for lead qualification, content generation, and decision automation." },
  { name: "CRM & Sales Automation", description: "GoHighLevel setup, pipelines, follow-up sequences, and speed-to-lead systems that convert more leads without more staff." },
  { name: "No-Code Workflow Engineering", description: "n8n, Make.com, and Zapier workflows that connect your entire stack \u2014 CRM, email, SMS, spreadsheets, payments, and internal tools." },
  { name: "AI-Assisted Development", description: "TypeScript & Python automation, MCP servers, Trigger.dev background jobs, and GitHub Actions CI/CD for production-grade custom automation." }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List the four core services Marwin offers: AI automation, CRM/sales automation, no-code workflow engineering, and AI-assisted development.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }]
  })
});

// src/lib/mcp/tools/list-case-studies.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
var caseStudies = [
  { title: "Vehicle Rental Service \u2014 Complete GHL Automation System", platform: "GoHighLevel", summary: "7 interconnected workflows covering lead intake, quotes/booking, confirmations, reply detection, no-reply follow-up, and post-rental review." },
  { title: "AI Job Scraper + Resume Optimizer", platform: "n8n", summary: "Scrapes job listings and generates AI-optimized resumes matching each posting." },
  { title: "Facebook Page AI Agent", platform: "n8n", summary: "AI agent that responds to Facebook page messages and comments in-brand." },
  { title: "Fitness Coach \u2014 Weekly Client Check-in", platform: "n8n", summary: "Automated weekly progress check-ins with AI-personalized coaching feedback." },
  { title: "Desmark FB Payment Monitor", platform: "n8n", summary: "Monitors Facebook page for payment confirmations and updates internal tracking." }
];
var list_case_studies_default = defineTool3({
  name: "list_case_studies",
  title: "List case studies",
  description: "List selected portfolio case studies and automation projects Marwin has built (GoHighLevel and n8n).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(caseStudies, null, 2) }]
  })
});

// src/lib/mcp/tools/list-tools-stack.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
var stack = {
  automation_platforms: ["GoHighLevel", "n8n", "Make.com", "Zapier"],
  ai_models: ["OpenAI / ChatGPT", "Anthropic Claude", "Google Gemini", "xAI Grok"],
  voice_ai: ["Vapi", "Retell AI", "ElevenLabs"],
  data_and_storage: ["Airtable", "Google Sheets", "Supabase", "Firebase", "Google Drive"],
  messaging: ["Slack", "Discord", "Telegram", "WhatsApp API", "Twilio", "Gmail API"],
  crm_and_sales: ["GoHighLevel", "HubSpot", "Pipedrive", "ActiveCampaign", "Mailchimp"],
  payments_ecommerce: ["Stripe", "Shopify"],
  dev_tooling: ["TypeScript", "Python", "Trigger.dev", "GitHub Actions", "MCP (Model Context Protocol)"],
  productivity: ["Notion", "ClickUp", "Trello", "Calendly"]
};
var list_tools_stack_default = defineTool4({
  name: "list_tools_stack",
  title: "List tools & platforms",
  description: "List the tools, platforms, and technologies Marwin works with, grouped by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(stack, null, 2) }]
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact info",
  description: "Get ways to reach Marwin: book a call, LinkedIn, Upwork, and the portfolio website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          book_a_call: "https://calendly.com/marwinemia0525/30min",
          website: "https://marwinai.com",
          published_portfolio: "https://marwinemia.lovable.app",
          message: "Book a free 30-minute discovery call to discuss your automation project."
        }, null, 2)
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "marwin-portfolio-mcp",
  title: "Marwin Emia \u2014 Portfolio MCP",
  version: "0.1.0",
  instructions: "Public MCP server for Marwin Emia's AI Automation portfolio. Use these tools to learn about Marwin's services, case studies, technology stack, and how to book a call.",
  tools: [get_profile_default, list_services_default, list_case_studies_default, list_tools_stack_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
